### ISSUE TITLE
create collection at series & subseries level

### ISSUE THREAD

**Issue by joshuago78** [gri-is/mets2man#4]

**Comment by joshuago78** [comment]
We need to discuss this with @azaroth42, Teresa, and Andra to figure out how we will get collections metadata (i.e. from Rosetta, which does not point from collections to items, or directly from the EAD, which would greatly complicate the simpler METS->manifest process)

**Comment by azaroth42** [comment]
And how to keep them up to date when new objects are added to collections.

What about if the collections were managed in a little dynamic system that could be POSTed to by the manifest writer to say "please add|remove (new manifest) to|from (existing collection)" and then as the manifests are generated or re-generated from the METS, ping the collection system?
